version: '3.9'

services:
  db:
    build:
      context: . 
      dockerfile: DockerFileMySql.dockerfile
    container_name: MySqlFinancialData
    ports:
      - "3306:3306" 
    expose: 
      - '3306'    
    volumes:
      - db_data:/var/lib/mysql 
    restart: always 

volumes:
  db_data: